version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: portfolia
      POSTGRES_PASSWORD: portfolia
      POSTGRES_DB: portfolia_production
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: portfolia
    build: .
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://portfolia:portfolia@db:5432/portfolia_production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      FORCE_SSL: "false" # change to true in production
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

volumes:
  db_data:
